# Generated by Django 5.2.8 on 2025-11-27 20:41

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('starter', 'Starter Plan'), ('standard', 'Standard Plan'), ('premium', 'Premium Plan')], max_length=50)),
                ('description', models.TextField()),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deposit_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fixed_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('user', 'User'), ('agent', 'Recovery Agent'), ('admin', 'Administrator')], default='user', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_kyc_verified', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ScamCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(default=core.models.generate_case_id, max_length=20, unique=True)),
                ('scam_type', models.CharField(choices=[('crypto', 'Crypto Scam'), ('banking', 'Online Banking Scam'), ('investment', 'Investment Scam'), ('trading', 'Trading/Forex Scam'), ('payment', 'Payment Fraud'), ('wallet', 'Stolen Wallet'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount_lost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('incident_date', models.DateField()),
                ('blockchain', models.CharField(blank=True, max_length=50, null=True)),
                ('victim_wallet', models.CharField(blank=True, max_length=255, null=True)),
                ('scammer_wallet', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('exchange_used', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_debited', models.CharField(blank=True, max_length=100, null=True)),
                ('beneficiary_details', models.TextField(blank=True, null=True)),
                ('suspect_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('suspect_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('suspect_website', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('investigation', 'Investigation Started'), ('tracing', 'Wallet/Account Tracing'), ('evidence', 'Evidence Gathering'), ('recovery', 'Recovery in Progress'), ('secured', 'Funds Secured'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('risk_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('payment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paymentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_recovered', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('recovery_method', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('recovery_date', models.DateField()),
                ('transaction_proof', models.FileField(blank=True, null=True, upload_to='recovery_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_transactions', to='core.scamcase')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('case_update', 'Case Update'), ('payment', 'Payment'), ('withdrawal', 'Withdrawal'), ('system', 'System'), ('message', 'Message')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.scamcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/%Y/%m/%d/')),
                ('file_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='core.scamcase')),
            ],
        ),
        migrations.CreateModel(
            name='CaseStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('investigation', 'Investigation Started'), ('tracing', 'Wallet/Account Tracing'), ('evidence', 'Evidence Gathering'), ('recovery', 'Recovery in Progress'), ('secured', 'Funds Secured'), ('completed', 'Completed'), ('rejected', 'Rejected')], max_length=20)),
                ('new_status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('investigation', 'Investigation Started'), ('tracing', 'Wallet/Account Tracing'), ('evidence', 'Evidence Gathering'), ('recovery', 'Recovery in Progress'), ('secured', 'Funds Secured'), ('completed', 'Completed'), ('rejected', 'Rejected')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='core.scamcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.scamcase')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_id', models.CharField(default=core.models.generate_deposit_id, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('crypto', 'Cryptocurrency'), ('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer')], max_length=10)),
                ('crypto_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('crypto_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='core.scamcase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='kyc/')),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('id_verified', models.BooleanField(default=False)),
                ('id_verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_recovered', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(default=core.models.generate_withdrawal_id, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('method', models.CharField(choices=[('bank', 'Bank Transfer'), ('crypto', 'Cryptocurrency'), ('paypal', 'PayPal'), ('cashapp', 'CashApp')], max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=100, null=True)),
                ('crypto_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('crypto_wallet', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cashapp_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
