# Generated by Django 5.2.8 on 2025-11-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether (USDT)'), ('USDC', 'USD Coin (USDC)')], max_length=10, unique=True)),
                ('wallet_address', models.CharField(max_length=255)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='crypto_qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdeposit',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='userdeposit',
            name='wallet_address',
        ),
        migrations.AddField(
            model_name='userdeposit',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdeposit',
            name='receipt_proof',
            field=models.FileField(blank=True, null=True, upload_to='deposit_receipts/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='userdeposit',
            name='crypto_currency',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether (USDT)'), ('USDC', 'USD Coin (USDC)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdeposit',
            name='payment_method',
            field=models.CharField(choices=[('crypto', 'Cryptocurrency')], default='crypto', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdeposit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('under_review', 'Under Review')], default='pending', max_length=15),
        ),
    ]
