# Generated by Django 5.2.8 on 2025-11-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('CHF', 'Swiss Franc (CHF)'), ('CNY', 'Chinese Yuan (¥)'), ('INR', 'Indian Rupee (₹)'), ('SGD', 'Singapore Dollar (S$)'), ('HKD', 'Hong Kong Dollar (HK$)'), ('NZD', 'New Zealand Dollar (NZ$)'), ('KRW', 'South Korean Won (₩)'), ('MXN', 'Mexican Peso ($)'), ('BRL', 'Brazilian Real (R$)'), ('RUB', 'Russian Ruble (₽)'), ('ZAR', 'South African Rand (R)'), ('TRY', 'Turkish Lira (₺)'), ('SEK', 'Swedish Krona (kr)'), ('NOK', 'Norwegian Krone (kr)'), ('DKK', 'Danish Krone (kr)'), ('PLN', 'Polish Złoty (zł)'), ('THB', 'Thai Baht (฿)'), ('IDR', 'Indonesian Rupiah (Rp)'), ('MYR', 'Malaysian Ringgit (RM)'), ('PHP', 'Philippine Peso (₱)'), ('VND', 'Vietnamese Đồng (₫)'), ('NGN', 'Nigerian Naira (₦)'), ('EGP', 'Egyptian Pound (E£)'), ('SAR', 'Saudi Riyal (﷼)'), ('AED', 'UAE Dirham (د.إ)'), ('QAR', 'Qatari Riyal (﷼)'), ('KWD', 'Kuwaiti Dinar (د.ك)'), ('BHD', 'Bahraini Dinar (.د.ب)')], default='USD', max_length=3),
        ),
    ]
