# Generated by Django 5.2.8 on 2025-12-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_preferred_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='RecoveryPro', max_length=200)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(default='support@recoverypro.com', max_length=254)),
                ('contact_phone', models.CharField(default='+1 (555) 123-4567', max_length=20)),
                ('support_email', models.EmailField(default='support@recoverypro.com', max_length=254)),
                ('sales_email', models.EmailField(default='sales@recoverypro.com', max_length=254)),
                ('company_name', models.CharField(default='RecoveryPro Inc.', max_length=200)),
                ('address_line1', models.CharField(default='123 Main Street', max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(default='New York', max_length=100)),
                ('state', models.CharField(default='NY', max_length=100)),
                ('zip_code', models.CharField(default='10001', max_length=20)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/favicon/')),
                ('site_icon', models.ImageField(blank=True, null=True, upload_to='site/icon/')),
                ('primary_color', models.CharField(default='#1e40af', help_text='Primary brand color in hex (#RRGGBB)', max_length=7)),
                ('secondary_color', models.CharField(default='#0ea5e9', help_text='Secondary brand color in hex', max_length=7)),
                ('accent_color', models.CharField(default='#10b981', help_text='Accent color for buttons, links', max_length=7)),
                ('business_hours', models.CharField(default='Monday - Friday: 9am - 6pm EST', max_length=200)),
                ('timezone', models.CharField(default='America/New_York', max_length=50)),
                ('default_currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('CHF', 'Swiss Franc (CHF)'), ('CNY', 'Chinese Yuan (¥)'), ('INR', 'Indian Rupee (₹)'), ('SGD', 'Singapore Dollar (S$)'), ('HKD', 'Hong Kong Dollar (HK$)'), ('NZD', 'New Zealand Dollar (NZ$)'), ('KRW', 'South Korean Won (₩)'), ('MXN', 'Mexican Peso ($)'), ('BRL', 'Brazilian Real (R$)'), ('RUB', 'Russian Ruble (₽)'), ('ZAR', 'South African Rand (R)'), ('TRY', 'Turkish Lira (₺)'), ('SEK', 'Swedish Krona (kr)'), ('NOK', 'Norwegian Krone (kr)'), ('DKK', 'Danish Krone (kr)'), ('PLN', 'Polish Złoty (zł)'), ('THB', 'Thai Baht (฿)'), ('IDR', 'Indonesian Rupiah (Rp)'), ('MYR', 'Malaysian Ringgit (RM)'), ('PHP', 'Philippine Peso (₱)'), ('VND', 'Vietnamese Đồng (₫)'), ('NGN', 'Nigerian Naira (₦)'), ('EGP', 'Egyptian Pound (E£)'), ('SAR', 'Saudi Riyal (﷼)'), ('AED', 'UAE Dirham (د.إ)'), ('QAR', 'Qatari Riyal (﷼)'), ('KWD', 'Kuwaiti Dinar (د.ك)'), ('BHD', 'Bahraini Dinar (.د.ب)')], default='USD', max_length=3)),
                ('min_deposit_amount', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('min_withdrawal_amount', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('email_signature', models.TextField(blank=True, null=True)),
                ('footer_text', models.TextField(default='© 2024 RecoveryPro. All rights reserved.')),
                ('terms_url', models.URLField(blank=True, null=True)),
                ('privacy_url', models.URLField(blank=True, null=True)),
                ('disclaimer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
